[project]
authors = ["aegroto <aegroto@protonmail.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "filters-in-python"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
python = "python"

format = "ruff format"
lint = "ruff check"

[dependencies]
python = ">=3.13.1,<4"

[pypi-dependencies]
python-ffmpeg = ">=2.0.12, <3"
scipy = ">=1.14.1, <2"
numpy = ">=2.1.3, <3"
ruff = ">=0.8.2, <0.9"
